In [1]:
import pandas as pd
alquiler_vivienda = pd.DataFrame(pd.read_csv(r"C:\Users\Eneko\Desktop\Ejercicios Data\Ejercicios\Proyecto EDA\EDA Correlacion del precio de la vivienda respecto al oro\CSV\Alquiler vivienda.csv",encoding='cp1252'))
fuente_7 = "https://www.idealista.com/sala-de-prensa/informes-precio-vivienda/alquiler/historico/"

In [2]:
alquiler_vivienda.info()

<class 'pandas.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Mes              242 non-null    str
 1   Precio €/m2      242 non-null    str
 2   Variación anual  242 non-null    str
dtypes: str(3)
memory usage: 5.8 KB

In [3]:
alquiler_vivienda.head() # Por un lado he trabajado el csv para corregir el formato fecha en PowerBI, y he quitado el simbolo de € del valor de la columna precio. Luego para mayor aclaración se lo he asignado al nombre de la columna y le he cambiado la codificación para poder mostrar el simbolo puesto que me lo corrompia.

        Mes Precio €/m2 Variación anual
0  01/02/26          15           7,80%
1  01/01/26          15           8,10%
2  01/12/25        14,7           8,50%
3  01/11/25        14,6           9,90%
4  01/10/25        14,5          10,90%

In [ ]:
# %d = día (01), %m = mes (02), %y = año en dos dígitos (26)
alquiler_vivienda['Mes'] = pd.to_datetime(alquiler_vivienda['Mes'], format='%d/%m/%y')

# Ahora, si quieres dejarlo visualmente como 2026-02:
alquiler_vivienda['Mes_formateado'] = alquiler_vivienda['Mes'].dt.strftime('%Y-%m')

In [4]:
alquiler_vivienda.head()

        Mes Precio €/m2 Variación anual
0  01/02/26          15           7,80%
1  01/01/26          15           8,10%
2  01/12/25        14,7           8,50%
3  01/11/25        14,6           9,90%
4  01/10/25        14,5          10,90%

In [ ]:
# alquiler_vivienda.to_csv('alquiler_vivienda_limpio.csv', index=False)

In [5]:
# Renombrar la columna de fecha a un nombre estándar (ej. 'fecha')
# Sustituye 'Nombre_Actual' por el nombre que tenga ahora esa columna
alquiler_vivienda =alquiler_vivienda.rename(columns={'Mes': 'DateTime'})

# Convertir esa columna a formato datetime
alquiler_vivienda['DateTime'] = pd.to_datetime(alquiler_vivienda['DateTime'])

# Crear la columna 'Anio' extrayendo el año del datetime
alquiler_vivienda['Anio'] = alquiler_vivienda['DateTime'].dt.year

# Sobrescribir el CSV original con los cambios
# Usamos index=False para que no te cree una columna de números extra
alquiler_vivienda.to_csv('archivo_original.csv', index=False)

print("¡Archivo actualizado correctamente con la columna Anio!")

¡Archivo actualizado correctamente con la columna Anio!

C:\Users\Eneko\AppData\Local\Temp\ipykernel_22612\60994848.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  alquiler_vivienda['DateTime'] = pd.to_datetime(alquiler_vivienda['DateTime'])

In [6]:
alquiler_vivienda.head()

    DateTime Precio €/m2 Variación anual  Anio
0 2026-01-02          15           7,80%  2026
1 2026-01-01          15           8,10%  2026
2 2025-01-12        14,7           8,50%  2025
3 2025-01-11        14,6           9,90%  2025
4 2025-01-10        14,5          10,90%  2025