In [4]:
import pandas as pd
compraventas = pd.read_csv(r'C:\Users\Eneko\Desktop\Ejercicios Data\Ejercicios\Proyecto EDA\EDA Correlacion del precio de la vivienda respecto al oro\CSV\Compraventas.csv', sep=';', encoding='utf-8-sig')
fuente_6 = "https://www.ine.es/consul/serie.do?d=true&s=ETDP377&c=2&"

In [5]:
compraventas.head()

,Variable1,Valor1,Variable2,Valor2,Variable3,Valor3,PERIODO,VALOR
0,Tipo de dato,Número,Naturaleza de la finca,Total fincas,Total Nacional,Total Nacional,2026M01,191.315
1,Tipo de dato,Número,Naturaleza de la finca,Total fincas,Total Nacional,Total Nacional,2025M12,193.802
2,Tipo de dato,Número,Naturaleza de la finca,Total fincas,Total Nacional,Total Nacional,2025M11,200.881
3,Tipo de dato,Número,Naturaleza de la finca,Total fincas,Total Nacional,Total Nacional,2025M10,221.889
4,Tipo de dato,Número,Naturaleza de la finca,Total fincas,Total Nacional,Total Nacional,2025M09,198.828

In [6]:
compraventas['Anio'] = compraventas['PERIODO'].str[:4].astype(int)

# Convertimos VALOR a número (el INE usa el punto como separador de MILES aquí)
compraventas['VALOR_Num'] = pd.to_numeric(
    compraventas['VALOR'].astype(str).str.replace('.', '', regex=False), 
    errors='coerce'
)

# 3. Agrupamos por Año (SUMA) 
# Al ser volumen, sumamos todos los meses para tener el total de ventas del año
compraventas_anual = compraventas.groupby('Anio')['VALOR_Num'].sum().reset_index()
compraventas_anual.columns = ['Anio', 'Total_Ventas']

In [7]:
compraventas_anual.head()

   Anio  Total_Ventas
0  2007       2508138
1  2008       1851890
2  2009       1549021
3  2010       1538101
4  2011       1648176

In [8]:
# 1. Aseguramos que los datos estén ordenados cronológicamente antes de calcular
compraventas_anual = compraventas_anual.sort_values('Anio')

# 2. Añadimos la columna de Variación Anual (%)
# (Valor actual - Valor anterior) / Valor anterior * 100
compraventas_anual['Var_Ventas_Pct'] = compraventas_anual['Total_Ventas'].pct_change() * 100

In [9]:
compraventas_anual.head()

   Anio  Total_Ventas  Var_Ventas_Pct
0  2007       2508138             NaN
1  2008       1851890      -26.164749
2  2009       1549021      -16.354589
3  2010       1538101       -0.704961
4  2011       1648176        7.156552

In [10]:
compraventas_anual.to_csv('compraventas_anual_final.csv', index=False, sep=';', encoding='utf-8-sig')