In [1]:
import pandas as pd
# guarda en variables los datasets y su fuente
df_euribor = pd.DataFrame(pd.read_csv(r"C:\Users\Eneko\Desktop\Ejercicios Data\Ejercicios\Proyecto EDA\EDA Correlacion del precio de la vivienda respecto al oro\CSV\Euribor 2015-2025.csv"))
fuente_1 = "https://www.epdata.es/datos/euribor-hoy-evolucion-historica-euribor-mensual-estadisticas-datos-hipotecas-variables/502"

In [2]:
df_euribor.info()

<class 'pandas.DataFrame'>
RangeIndex: 315 entries, 0 to 314
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Fecha              315 non-null    str
 1   Media mensual (%)  315 non-null    float64
dtypes: float64(1), str(1)
memory usage: 5.1 KB

In [3]:
df_euribor.head()

    Fecha  Media mensual (%)
0  ene-99              3.062
1  feb-99              3.030
2  mar-99              3.046
3  abr-99              2.756
4  may-99              2.683

In [4]:
# Diccionario de traducción
meses_es_en = {
    'ene': 'Jan', 'feb': 'Feb', 'mar': 'Mar', 'abr': 'Apr',
    'may': 'May', 'jun': 'Jun', 'jul': 'Jul', 'ago': 'Aug',
    'sep': 'Sep', 'oct': 'Oct', 'nov': 'Nov', 'dic': 'Dec'
}

# 1. Aseguramos que el mes esté en inglés (usando el diccionario que ya tienes)
df_euribor['mes_en'] = df_euribor['Fecha'].str[:3].str.lower().map(meses_es_en)

# 2. Extraemos el año saltando el posible guion original
# Si tus datos son 'ene-99', el año empieza en la posición 4. 
# Si son 'ene99', empieza en la 3.
# Esta línea busca solo los números:
df_euribor['anio_num'] = df_euribor['Fecha'].str.extract('(\d+)')

# 3. Concatenamos SIN guion extra y usamos el formato '%b%y'
df_euribor['fecha_dt'] = pd.to_datetime(df_euribor['mes_en'] + df_euribor['anio_num'], format='%b%y')

In [5]:
# Filtrar entre el 1 de enero de 2015 y el 31 de diciembre de 2025
mask = (df_euribor['fecha_dt'] >= '2015-01-01') & (df_euribor['fecha_dt'] <= '2025-12-31')
df_euribor_filtrado = df_euribor.loc[mask]
df_euribor_filtrado.head()

      Fecha  Media mensual (%) mes_en anio_num   fecha_dt
192  ene-15              0.298    Jan       15 2015-01-01
193  feb-15              0.255    Feb       15 2015-02-01
194  mar-15              0.212    Mar       15 2015-03-01
195  abr-15              0.180    Apr       15 2015-04-01
196  may-15              0.165    May       15 2015-05-01

In [6]:
df_euribor['fecha_dt'] = pd.to_datetime(df_euribor['fecha_dt'])

# Quitar los días (Convertir a Periodo de Mes y luego a Texto YYYY-MM)
df_euribor['fecha_dt'] = df_euribor['fecha_dt'].dt.strftime('%Y-%m')

In [7]:
df_euribor.head()

    Fecha  Media mensual (%) mes_en anio_num fecha_dt
0  ene-99              3.062    Jan       99  1999-01
1  feb-99              3.030    Feb       99  1999-02
2  mar-99              3.046    Mar       99  1999-03
3  abr-99              2.756    Apr       99  1999-04
4  may-99              2.683    May       99  1999-05

In [ ]:
#df_euribor.to_csv('euribor_mes_limpio.csv', index=False)

In [8]:
# Renombrar la columna de fecha a un nombre estándar (ej. 'fecha')
# Sustituye 'Nombre_Actual' por el nombre que tenga ahora esa columna
df_euribor =df_euribor.rename(columns={'fecha_dt': 'DateTime'})

# Convertir esa columna a formato datetime
df_euribor['DateTime'] = pd.to_datetime(df_euribor['DateTime'])

# Crear la columna 'Anio' extrayendo el año del datetime
df_euribor['Anio'] = df_euribor['DateTime'].dt.year

# Sobrescribir el CSV original con los cambios
# Usamos index=False para que no te cree una columna de números extra
df_euribor.to_csv('euribor_final.csv', index=False)

print("¡Archivo actualizado correctamente con la columna Anio!")

¡Archivo actualizado correctamente con la columna Anio!

In [9]:
df_euribor.head()

    Fecha  Media mensual (%) mes_en anio_num   DateTime  Anio
0  ene-99              3.062    Jan       99 1999-01-01  1999
1  feb-99              3.030    Feb       99 1999-02-01  1999
2  mar-99              3.046    Mar       99 1999-03-01  1999
3  abr-99              2.756    Apr       99 1999-04-01  1999
4  may-99              2.683    May       99 1999-05-01  1999