In [6]:
import pandas as pd
poder_adquisitivo =pd.DataFrame(pd.read_csv(r"C:\Users\Eneko\Desktop\Ejercicios Data\Ejercicios\Proyecto EDA\EDA Correlacion del precio de la vivienda respecto al oro\CSV\Salario mediano anual.csv",sep=';', encoding='utf-8'))
fuente_8 = "https://www.ine.es/jaxiT3/Datos.htm?t=66199#_tabs-tabla"

In [7]:
poder_adquisitivo.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 5 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Tipo de jornada              19 non-null     str
 1   Decil                        19 non-null     int64
 2   Valor absoluto y porcentaje  19 non-null     str
 3   Periodo                      19 non-null     int64
 4   Total                        19 non-null     str
dtypes: int64(2), str(3)
memory usage: 892.0 bytes

In [8]:
poder_adquisitivo.head()

,Tipo de jornada,Decil,Valor absoluto y porcentaje,Periodo,Total
0,Jornada a tiempo completo,5,Valor absoluto,2024,"1.767,6"
1,Jornada a tiempo completo,5,Valor absoluto,2023,"1.736,2"
2,Jornada a tiempo completo,5,Valor absoluto,2022,"1.673,0"
3,Jornada a tiempo completo,5,Valor absoluto,2021,"1.601,3"
4,Jornada a tiempo completo,5,Valor absoluto,2020,"1.535,9"

In [9]:
# Renombrar la columna de fecha a un nombre estándar (ej. 'fecha')
# Sustituye 'Nombre_Actual' por el nombre que tenga ahora esa columna
poder_adquisitivo =poder_adquisitivo.rename(columns={'Periodo': 'DateTime'})

# Convertir esa columna a formato datetime
poder_adquisitivo['DateTime'] = pd.to_datetime(poder_adquisitivo['DateTime'])

# Crear la columna 'Anio' extrayendo el año del datetime
poder_adquisitivo['Anio'] = poder_adquisitivo['DateTime'].dt.year

# Sobrescribir el CSV original con los cambios
# Usamos index=False para que no te cree una columna de números extra
poder_adquisitivo.to_csv('poder_adquisitivo_final.csv', index=False)

print("¡Archivo actualizado correctamente con la columna Anio!")

¡Archivo actualizado correctamente con la columna Anio!

In [10]:
poder_adquisitivo.head()

,Tipo de jornada,Decil,Valor absoluto y porcentaje,DateTime,Total,Anio
0,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002024,"1.767,6",1970
1,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002023,"1.736,2",1970
2,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002022,"1.673,0",1970
3,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002021,"1.601,3",1970
4,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002020,"1.535,9",1970

In [11]:
# 1. Extraer el año real de la columna DateTime (los últimos 4 caracteres)
poder_adquisitivo['Anio'] = poder_adquisitivo['DateTime'].astype(str).str[-4:].astype(int)

# 2. Limpiar la columna Total (Ej: '1.767,6' -> 1767.6)
# Quitamos el punto de miles y cambiamos la coma por punto
poder_adquisitivo['Total_Num'] = (poder_adquisitivo['Total']
                       .str.replace('.', '', regex=False)
                       .str.replace(',', '.', regex=False)
                       .astype(float))

# 3. Anualizar salario (Mensual * 12)
poder_adquisitivo['Salario_Anual_Real'] = poder_adquisitivo['Total_Num'] * 12

In [12]:
poder_adquisitivo.to_csv('poder_adquisitivo_final.csv', index=False)

In [13]:
poder_adquisitivo.head()

,Tipo de jornada,Decil,Valor absoluto y porcentaje,DateTime,Total,Anio,Total_Num,Salario_Anual_Real
0,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002024,"1.767,6",2024,1767.6,21211.2
1,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002023,"1.736,2",2023,1736.2,20834.4
2,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002022,"1.673,0",2022,1673.0,20076.0
3,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002021,"1.601,3",2021,1601.3,19215.6
4,Jornada a tiempo completo,5,Valor absoluto,1970-01-01 00:00:00.000002020,"1.535,9",2020,1535.9,18430.8