In [1]:
import yfinance as yf
import seaborn as sns
import matplotlib as plt
import pandas as pd

In [2]:
df_oro_dolares = yf.download("GC=F", period="10y")

df_oro_dolares.columns = df_oro_dolares.columns.get_level_values(0)

df_oro_dolares = df_oro_dolares.reset_index()

df_oro_dolares.head()

[*********************100%***********************]  1 of 1 completed

Price       Date        Close         High          Low         Open  Volume
0     2016-04-08  1242.500000  1242.800049  1232.000000  1241.000000     409
1     2016-04-11  1256.699951  1258.699951  1241.500000  1241.500000     437
2     2016-04-12  1259.400024  1261.699951  1253.699951  1260.000000     185
3     2016-04-13  1246.800049  1256.900024  1241.300049  1256.500000     203
4     2016-04-14  1225.000000  1243.699951  1224.500000  1231.400024     264

In [3]:
# 1. Descarga de datos del oro (USD) y del tipo de cambio (EUR/USD)
df_oro_dolares = yf.download("GC=F", period="10y")
df_eur_usd = yf.download("EURUSD=X", period="10y")

# 2. Limpiar niveles de columnas
df_oro_dolares.columns = df_oro_dolares.columns.get_level_values(0)
df_eur_usd.columns = df_eur_usd.columns.get_level_values(0)

# 3. Crear el nuevo DataFrame en Euros
# Dividimos el precio en dólares por el valor del tipo de cambio
df_oro_euros = df_oro_dolares.copy()
df_oro_euros['Close'] = df_oro_dolares['Close'] / df_eur_usd['Close']

# 4. Resetear índice si lo necesitas
df_oro_euros = df_oro_euros.reset_index()

df_oro_euros.head()

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Price       Date        Close         High          Low         Open  Volume
0     2016-04-08  1092.405988  1242.800049  1232.000000  1241.000000     409
1     2016-04-11  1102.075558  1258.699951  1241.500000  1241.500000     437
2     2016-04-12  1103.486384  1261.699951  1253.699951  1260.000000     185
3     2016-04-13  1095.126837  1256.900024  1241.300049  1256.500000     203
4     2016-04-14  1086.085056  1243.699951  1224.500000  1231.400024     264

In [4]:
# 1. Aseguramos que la fecha sea datetime (yfinance suele traerla en el índice o como 'Date')
# Si la fecha es el índice, usa: df_oro = df_oro.reset_index()
df_oro_euros['Date'] = pd.to_datetime(df_oro_euros['Date'])

# 2. Creamos la columna con el formato 'YYYY-MM' (la que usaremos para el merge)
df_oro_euros['Mes'] = df_oro_euros['Date'].dt.strftime('%Y-%m')

# 3. Calculamos la MEDIA MENSUAL del precio (ej. de la columna 'Close')
# Agrupamos por la nueva columna 'Mes' y calculamos la media
df_oro_mensual = df_oro_euros.groupby('Mes')['Close'].mean().reset_index()

# 4. Renombramos la columna para que se entienda que es una media
df_oro_mensual = df_oro_mensual.rename(columns={'Close': 'oro_media_mensual'})

# 5. Ver el resultado y exportar
df_oro_mensual.head()

       Mes  oro_media_mensual
0  2016-04        1102.007590
1  2016-05        1112.271385
2  2016-06        1135.730955
3  2016-07        1209.335225
4  2016-08        1193.973885

In [5]:
df_oro_mensual.to_csv('oro_mensual_limpio.csv', index=False)

In [6]:
# Renombrar la columna de fecha a un nombre estándar (ej. 'fecha')
# Sustituye 'Nombre_Actual' por el nombre que tenga ahora esa columna
df_oro_mensual =df_oro_mensual.rename(columns={'Mes': 'DateTime'})

# Convertir esa columna a formato datetime
df_oro_mensual['DateTime'] = pd.to_datetime(df_oro_mensual['DateTime'])

# Crear la columna 'Anio' extrayendo el año del datetime
df_oro_mensual['Anio'] = df_oro_mensual['DateTime'].dt.year

# Sobrescribir el CSV original con los cambios
# Usamos index=False para que no te cree una columna de números extra
df_oro_mensual.to_csv('oro_final.csv', index=False)

print("¡Archivo actualizado correctamente con la columna Anio!")

¡Archivo actualizado correctamente con la columna Anio!

In [7]:
df_oro_mensual.head()

    DateTime  oro_media_mensual  Anio
0 2016-04-01        1102.007590  2016
1 2016-05-01        1112.271385  2016
2 2016-06-01        1135.730955  2016
3 2016-07-01        1209.335225  2016
4 2016-08-01        1193.973885  2016