In [1]:
import pandas as pd
df_precio_vivienda = pd.DataFrame(pd.read_csv(r"C:\Users\Eneko\Desktop\Ejercicios Data\Ejercicios\Proyecto EDA\EDA Correlacion del precio de la vivienda respecto al oro\CSV\Evolucion precio vivienda.csv",encoding='cp1252', sep=','))
fuente_3 = "https://www.idealista.com/sala-de-prensa/informes-precio-vivienda/venta/historico/"

In [2]:
df_precio_vivienda.info()

<class 'pandas.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Mes              242 non-null    str
 1   Precio €/m2      242 non-null    str
 2   Variación anual  242 non-null    str
dtypes: str(3)
memory usage: 5.8 KB

In [3]:
df_precio_vivienda.head() # Modificado con PowerBi para quitarle el simbolo de €/m2 a las filas y añadido a la columna.

        Mes Precio €/m2 Variación anual
0  01/02/26        2673          17,70%
1  01/01/26        2650          18,40%
2  01/12/25        2639          16,20%
3  01/11/25        2605          16,10%
4  01/10/25        2555          15,70%

In [4]:
# 1. Convertimos detectando automáticamente ambos formatos
df_precio_vivienda['Mes'] = pd.to_datetime(df_precio_vivienda['Mes'], dayfirst=True, format='mixed')

# 2. Ahora que todos son fechas reales, unificamos visualmente a YYYY-MM
df_precio_vivienda['Mes'] = df_precio_vivienda['Mes'].dt.strftime('%Y-%m')

In [5]:
df_precio_vivienda.head()

       Mes Precio €/m2 Variación anual
0  2026-02        2673          17,70%
1  2026-01        2650          18,40%
2  2025-12        2639          16,20%
3  2025-11        2605          16,10%
4  2025-10        2555          15,70%

In [ ]:
#df_precio_vivienda.to_csv('precio_vivienda_limpio.csv', index=False)

In [6]:
# Renombrar la columna de fecha a un nombre estándar (ej. 'fecha')
# Sustituye 'Nombre_Actual' por el nombre que tenga ahora esa columna
df_precio_vivienda =df_precio_vivienda.rename(columns={'Mes': 'DateTime'})

# Convertir esa columna a formato datetime
df_precio_vivienda['DateTime'] = pd.to_datetime(df_precio_vivienda['DateTime'])

# Crear la columna 'Anio' extrayendo el año del datetime
df_precio_vivienda['Anio'] = df_precio_vivienda['DateTime'].dt.year

# Sobrescribir el CSV original con los cambios
# Usamos index=False para que no te cree una columna de números extra
df_precio_vivienda.to_csv('precio_vivienda_final.csv', index=False)

print("¡Archivo actualizado correctamente con la columna Anio!")

¡Archivo actualizado correctamente con la columna Anio!

In [7]:
df_precio_vivienda.head()

    DateTime Precio €/m2 Variación anual  Anio
0 2026-02-01        2673          17,70%  2026
1 2026-01-01        2650          18,40%  2026
2 2025-12-01        2639          16,20%  2025
3 2025-11-01        2605          16,10%  2025
4 2025-10-01        2555          15,70%  2025